apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.data.name }}
spec:
  {{- if not .Values.shared.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.redis.data.name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.redis.data.name }}
    spec:
      containers:
        - name: {{ .Values.redis.data.name }}
          image: redis
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.port }}
              protocol: TCP
      nodeSelector:
        "beta.kubernetes.io/os": linux
