apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.data.name }}
spec:
  ports:
    - port: {{ .Values.redis.service.port }}
      protocol: TCP
      name: redis
  selector:
    app: {{ .Values.redis.data.name }}
