apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontEnd.data.name }}
spec:
  loadBalancerIP: {{ .Values.frontEnd.service.ip }}
  type: {{ .Values.frontEnd.service.type }}
  ports:
    - port: {{ .Values.frontEnd.service.port }}
      name: http
      targetPort: {{ .Values.frontEnd.service.port }}
  selector:
    app: {{ .Values.frontEnd.data.name }}
